[package]
name = "ferritin-cloud"
edition.workspace = true
version.workspace = true

[dependencies]
ferritin-core = { path = "../ferritin-core" }
aws-config = "1"
aws-sdk-s3 = "1"
aws-sdk-sqs = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
sha2 = "0.10"
base64 = "0.22"

[dev-dependencies]
testcontainers = { version = "0.27", features = ["blocking"] }
testcontainers-modules = { version = "0.15", features = ["localstack"] }
